name: build and test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Build & Run Tests
        run: ./gradlew clean build